apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: berg-project
  namespace: argocd
spec:
  destinations:
    - namespace: guestbook
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/argoproj/argocd-example-apps.git
