apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-test
spec:
  project: moonbeam-test--berg-ethos-caas-next-deploy-project-1
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    path: guestbook
    targetRevision: HEAD
  destination:
    namespace: guestbook
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
