apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: moonbeam-test--berg-ethos-caas-next-deploy-project-1
  namespace: argocd
spec:
  destinations:
  - namespace: guestbook
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/argoproj/argocd-example-apps.git
